package model;
// Generated 29 Dec, 2016 11:26:17 AM by Hibernate Tools 3.2.1.GA



/**
 * Bookdetails generated by hbm2java
 */
public class Bookdetails  implements java.io.Serializable {


     private Integer bookId;
     private int stockId;
     private String bookName;
     private String authorName;

    public Bookdetails() {
    }

    public Bookdetails(int stockId, String bookName, String authorName) {
       this.stockId = stockId;
       this.bookName = bookName;
       this.authorName = authorName;
    }
   
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }




}


