package model;
// Generated 29 Dec, 2016 11:26:17 AM by Hibernate Tools 3.2.1.GA



/**
 * Employeedetails generated by hbm2java
 */
public class Employeedetails  implements java.io.Serializable {


     private Integer empId;
     private String name;
     private String doB;
     private String address;
     private String pincode;
     private String phNo;
     private String emailId;
     private String userName;
     private String password;

    public Employeedetails() {
    }

    public Employeedetails(String name, String doB, String address, String pincode, String phNo, String emailId, String userName, String password) {
       this.name = name;
       this.doB = doB;
       this.address = address;
       this.pincode = pincode;
       this.phNo = phNo;
       this.emailId = emailId;
       this.userName = userName;
       this.password = password;
    }
   
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDoB() {
        return this.doB;
    }
    
    public void setDoB(String doB) {
        this.doB = doB;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getPhNo() {
        return this.phNo;
    }
    
    public void setPhNo(String phNo) {
        this.phNo = phNo;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


