package model;
// Generated 29 Dec, 2016 11:26:17 AM by Hibernate Tools 3.2.1.GA



/**
 * Issuedbookdetails generated by hbm2java
 */
public class Issuedbookdetails  implements java.io.Serializable {


     private Integer id;
     private int bookId;
     private int userId;
     private String issueDate;
     private String actReturnDate;

    public Issuedbookdetails() {
    }

    public Issuedbookdetails(int bookId, int userId, String issueDate, String actReturnDate) {
       this.bookId = bookId;
       this.userId = userId;
       this.issueDate = issueDate;
       this.actReturnDate = actReturnDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }
    public String getActReturnDate() {
        return this.actReturnDate;
    }
    
    public void setActReturnDate(String actReturnDate) {
        this.actReturnDate = actReturnDate;
    }




}


