package model;
// Generated 29 Dec, 2016 11:26:17 AM by Hibernate Tools 3.2.1.GA



/**
 * Returnbookdetails generated by hbm2java
 */
public class Returnbookdetails  implements java.io.Serializable {


     private Integer id;
     private int bookId;
     private int userId;
     private String returnDate;
     private String isFined;

    public Returnbookdetails() {
    }

    public Returnbookdetails(int bookId, int userId, String returnDate, String isFined) {
       this.bookId = bookId;
       this.userId = userId;
       this.returnDate = returnDate;
       this.isFined = isFined;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(String returnDate) {
        this.returnDate = returnDate;
    }
    public String getIsFined() {
        return this.isFined;
    }
    
    public void setIsFined(String isFined) {
        this.isFined = isFined;
    }




}


